services:
  app:
    build:
      context: .
      target: dev # Use the 'dev' stage in Dockerfile
    image: zms-dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true" # Enable file watching in Docker
      HOST: "0.0.0.0"
    volumes:
      - .:/app # Mount local files into the container
      - /app/node_modules # Prevent overwriting node_modules
    command: npm run dev # Use npm for development
